[package]
name = "anbernic-building"
version = "0.1.0"
edition = "2024"

[features]
default = ["alloc"]
alloc = []

[dependencies]
color-eyre = { version= "0.6.5"}
eyre = { version = "0.6.12"}
fern = { version = "0.7.1", features = ["colored"] }
humantime = "2.3.0"
log = "0.4.29"
pollster = "0.4.0"
sdl2 = { version = "0.38.0", features = ["raw-window-handle"] }

[dependencies.wgpu]
version = "27.0.1"

[target.aarch64-unknown-linux-musl.dependencies.sdl2]
version = "0.38.0"
features = [	
	"raw-window-handle",
	"static-link",
	"bundled",
	# "use-pkgconfig",
]
